package com.wisp.app.nostr

import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Byte-for-byte conformance with the zap.cooking frontend NIP-98 reference
 * (`src/lib/nip98.ts`). Golden values were generated by running that
 * module's exact logic (normalizeUrl / sha256Hex / authEvent encoding) in
 * Node — see ZAPCOOKING_ANDROID_BUILD.md §1. If the verifier and this
 * client ever diverge on URL canonicalization, method casing, payload
 * hashing, or JSON key order, these assertions fail before a request ever
 * hits the network.
 *
 * Runs on the plain JVM: [Nip98] depends only on java.util.Base64,
 * java.security.MessageDigest, and kotlinx-serialization — no Android
 * framework and no native secp256k1 (signing is exercised on-device).
 */
class Nip98Test {

    @Test
    fun normalizeUrl_dropsQueryAndFragment() {
        assertEquals(
            "https://zap.cooking/api/membership/check-status",
            Nip98.normalizeUrl("https://zap.cooking/api/membership/check-status?pubkey=abc&x=1")
        )
    }

    @Test
    fun normalizeUrl_stripsTrailingSlashOnNonRoot() {
        assertEquals(
            "https://zap.cooking/api/extract-recipe",
            Nip98.normalizeUrl("https://zap.cooking/api/extract-recipe/")
        )
    }

    @Test
    fun normalizeUrl_keepsRootSlash_evenWhenAbsent() {
        // JS `new URL('https://zap.cooking').pathname` === '/'.
        assertEquals("https://zap.cooking/", Nip98.normalizeUrl("https://zap.cooking"))
        assertEquals("https://zap.cooking/", Nip98.normalizeUrl("https://zap.cooking/"))
    }

    @Test
    fun normalizeUrl_passesThroughCanonicalUrl() {
        assertEquals(
            "https://zap.cooking/api/membership/check-status",
            Nip98.normalizeUrl("https://zap.cooking/api/membership/check-status")
        )
    }

    @Test
    fun sha256Hex_matchesFrontendPayloadTag() {
        val body = "{\"pubkey\":\"79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798\"}"
        assertEquals(
            "5cce3a5f4dee312cc4272163bb61a5f35186a1b99f4d1c7d1bd88f5a80b48f69",
            Nip98.sha256Hex(body.toByteArray(Charsets.UTF_8))
        )
    }

    @Test
    fun buildTags_uppercasesMethodAndAddsPayload() {
        val tags = Nip98.buildTags(
            method = "post",
            url = "https://zap.cooking/api/membership/check-status?z=1",
            bodyString = "{\"pubkey\":\"79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798\"}"
        )
        assertEquals(
            listOf(
                listOf("u", "https://zap.cooking/api/membership/check-status"),
                listOf("method", "POST"),
                listOf("payload", "5cce3a5f4dee312cc4272163bb61a5f35186a1b99f4d1c7d1bd88f5a80b48f69"),
            ),
            tags
        )
    }

    @Test
    fun buildTags_omitsPayloadWhenNoBody() {
        val tags = Nip98.buildTags("GET", "https://zap.cooking/api/membership/check-status", null)
        assertEquals(
            listOf(
                listOf("u", "https://zap.cooking/api/membership/check-status"),
                listOf("method", "GET"),
            ),
            tags
        )
    }

    @Test
    fun encodeAuthHeader_matchesFrontendByteForByte() {
        // Fixed, fully-specified signed event (sig is a stand-in — only the
        // serialization + base64 are under test here; signature validity is
        // verified by the on-device round-trip against check-status).
        val event = NostrEvent(
            id = "d1a2b3c4d5e6f70819a2b3c4d5e6f70819a2b3c4d5e6f70819a2b3c4d5e6f708",
            pubkey = "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
            created_at = 1718600000L,
            kind = Nip98.KIND,
            tags = listOf(
                listOf("u", "https://zap.cooking/api/membership/check-status"),
                listOf("method", "POST"),
                listOf("payload", "5cce3a5f4dee312cc4272163bb61a5f35186a1b99f4d1c7d1bd88f5a80b48f69"),
            ),
            content = "",
            sig = "0123456789abcdef".repeat(8),
        )
        val expected = "Nostr eyJpZCI6ImQxYTJiM2M0ZDVlNmY3MDgxOWEyYjNjNGQ1ZTZmNzA4MTlhMmIzYzRkNWU2" +
            "ZjcwODE5YTJiM2M0ZDVlNmY3MDgiLCJwdWJrZXkiOiI3OWJlNjY3ZWY5ZGNiYmFjNTVhMDYyOTVjZTg3MGIw" +
            "NzAyOWJmY2RiMmRjZTI4ZDk1OWYyODE1YjE2ZjgxNzk4IiwiY3JlYXRlZF9hdCI6MTcxODYwMDAwMCwia2lu" +
            "ZCI6MjcyMzUsInRhZ3MiOltbInUiLCJodHRwczovL3phcC5jb29raW5nL2FwaS9tZW1iZXJzaGlwL2NoZWNr" +
            "LXN0YXR1cyJdLFsibWV0aG9kIiwiUE9TVCJdLFsicGF5bG9hZCIsIjVjY2UzYTVmNGRlZTMxMmNjNDI3MjE2" +
            "M2JiNjFhNWYzNTE4NmExYjk5ZjRkMWM3ZDFiZDg4ZjVhODBiNDhmNjkiXV0sImNvbnRlbnQiOiIiLCJzaWci" +
            "OiIwMTIzNDU2Nzg5YWJjZGVmMDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nzg5YWJj" +
            "ZGVmMDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nzg5YWJjZGVmMDEyMzQ1Njc4OWFi" +
            "Y2RlZiJ9"
        assertEquals(expected, Nip98.encodeAuthHeader(event))
    }
}
